### ISSUE TITLE
iOS 10 support without of storyboards?

### ISSUE THREAD

**Issue by gerchicov-bp** [chanonly123/AutoKeyboard#4]
iOS 10 hasn't "safe area" and in the same time xibs haven't "bottomLayoutGuide". What to do in this case?

What about to allow to specify any other constraint instead of predefined ones?

**Comment by chanonly123** [comment]
Thank for sharing, Im busy this weekend, monday maybe or pull requests are always welcome.

**Comment by chanonly123** [comment]
Added ability to register other constraints and also to disable.
